### ISSUE TITLE
Base Colors & Alpha Colors Conflict

### ISSUE THREAD

**Issue by jd-carroll** [viktorbonino/radix-themes-tw#1]
The result of this line is that you only end up with the alpha colors:
https://github.com/viktorbonino/radix-themes-tw/blob/59928a5019d10b8b4acba2748987f73fc5a39332/src/index.ts#L65

Is that the intention? (Still trying to figure out themes)

**Comment by viktorbonino** [comment]
I fixed it. Upgrade the package and should work. I forgot to add an A on the alpha colors name.
Now you can access both colors and alpha colors.
For example(with bg utility):
```
bg-red-5
```
```
bg-redA-5
```

**Comment by techAffinate** [comment]
How do we access alpha for bg-accent?
