### ISSUE TITLE
Missing font weights in the preset

### ISSUE THREAD

**Issue by ByteCrak07** [viktorbonino/radix-themes-tw#10]
I found this library very useful with Radix Themes. But I noticed that in the config there are some missing fontWeights which were in the default tailwind config. Are those omitted on purpose or is it a small mistake while implementing the preset? If its a small mistake I can open a PR if you would like. Thanks

**Comment by viktorbonino** [comment]
Hi, the preset is meant to follow radix design system and so it only includes the font weights used in radix themes.
