### ISSUE TITLE
Support for version 3.0.0

### ISSUE THREAD

**Issue by eseyfert** [viktorbonino/radix-themes-tw#18]
Hey there, first of all, thanks for this nifty library. 🙏
A few days ago version `3.0.0` released for Radix-UI: https://www.radix-ui.com/themes/docs/overview/releases

Any plans to make this library compatible with their changes?

**Comment by viktorbonino** [comment]
Yes. When i have time i will update it. 
There are some changes to the css vars, so i need update it and test it.

**Comment by eseyfert** [comment]
Thanks a lot, looking forward to it!

**Comment by viktorbonino** [comment]
I updated the preset. 
Some tokens are not available yet (i think that most of them are not needed in a tailwind preset), but tell me if you need some that are not available but that could be useful.

**Comment by eseyfert** [comment]
Thanks a lot, I'll take a look when I get a moment!

**Comment by eseyfert** [comment]
Sorry for the late response, but its all working just fine on my end.
Thanks again for the quick update! 🎉
