### ISSUE TITLE
How can I assign custom colors in themes and have them reflected in tailwind colors?

### ISSUE THREAD

**Issue by jonschmidt** [viktorbonino/radix-themes-tw#20]
I am having some trouble getting this plugin to do what I think it should be doing, and I believe it is because of the way my global css file (the input css file of tailwind) is setup. 

If I want to override a bunch of tokens in themes (including color tokens), at what point should I be doing that? I assume this has to be reflected in the input css file of tailwind, so that this plugin can do the correct things?

I think a huge addition here would be to have an example of what a css file might look like that is setup properly, but I understand most might not be struggling here.

**Comment by viktorbonino** [comment]
Hi, there's a great overview on how to override and style radix-themes components in the radix documentation.
Here's the link: https://www.radix-ui.com/themes/docs/overview/styling

If you want to override tokens you can do it in the input css file of tailwind.

I will also update the readme on how to properly import tailwind and radix themes styles.
