### ISSUE TITLE
Spacing is not consistent

### ISSUE THREAD

**Issue by toniopelo** [viktorbonino/radix-themes-tw#5]
When using spacing from radix theme (meaning, using the `mt`, `mb`, `mx`, etc properties from the radix components) you don't get the same spacing than with the `mt-x`, `mb-x`, etc classes from tailwind.

Example:
```
<Button mt="3">Modifier</Button>
```
is not equivalent to
```
<Button className="mt-3">Modifier</Button>
```
and that's a shame because that would be a lot easier to have consistent spacing across the app.

Thanks for this nice preset :)

**Comment by viktorbonino** [comment]
For spacing i decided to extend the tailwind spacing, instead of replacing it because radix spacing is a bit limited.
So to use the radix spacing you need to use for example `mt-rx-3` instead of `mt-3`.

**Comment by toniopelo** [comment]
Oh, nice, I didn't see that. That's absolutely fine by me then.
I'll close this thanks!
