### ISSUE TITLE
Typescript complains it can't find the type definitions

### ISSUE THREAD

**Issue by mikey0000** [viktorbonino/radix-themes-tw#6]
TS2307: Cannot find module  radix-themes-tw  or its corresponding type declarations.

typescript 5.2.2

**Comment by viktorbonino** [comment]
Can you give me more details? Are you sure that everything is installed correctly?

**Comment by mikey0000** [comment]
its a nextjs project with the following eslintrc
```
{
  "extends": "next/core-web-vitals",
  "rules": {
    "indent": [
      "error", "tab"
    ]
  },
  "plugins": [
    "import"
  ]
}
```
tsconfig
```
{
  "compilerOptions": {
    "target": "es6",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "typeRoots": [
      "./types"
    ],
    "rootDir": "./",
    "paths": {
      "@/*": [
        "./*"
      ]
    },
    "plugins": [
      {
        "name": "next"
      }
    ]
  },
  "include": [
    "next-env.d.ts",
    "./**/*.ts",
    "./**/*.tsx",
    ".next/types/**/*.ts",
    "dist/types/**/*.ts"
  ],
  "exclude": [
    "node_modules"
  ]
}
```

**Comment by mikey0000** [comment]
all my other imports are fine, its just this one. I'm stumped as to why, intellij can find the type files etc but it always fails on compile/build

**Comment by jcsmithf22** [comment]
I have the exact issue, on a fresh typescript install of vite with react. Also, the presets do not seem to be working or showing up in intellisense.

**Comment by viktorbonino** [comment]
@mikey0000 if you're using ts extension on tailwind config (tailwind.config.ts), you need to have `"moduleResolution": "bundler"`.

**Comment by viktorbonino** [comment]
@jcsmithf22 can you share your tsconfig and tailwind config?
